name: Windows Build and Push Executable

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Executable for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install WiX Toolset via Chocolatey
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install wixtoolset -y --no-progress
          $env:PATH = "C:\Program Files (x86)\WiX Toolset v3.11\bin;$env:PATH"
          echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Grant gradlew execute permission
        shell: bash
        run: chmod +x gradlew

      - name: Build with Gradle
        run: .\gradlew.bat build shadowJar --info

      - name: Create output directory
        run: mkdir -p whisperer-windows

      - name: Create Windows executable
        shell: pwsh
        run: |
          $jdkPath = "$env:JAVA_HOME"
          & "$jdkPath\bin\jpackage" `
            --input build/libs `
            --main-jar Whisprer-1.0.jar `
            --main-class com.example.whisprer.LauncherKt `
            --name "Whisperer" `
            --type msi `
            --win-shortcut `
            --win-menu `
            --win-dir-chooser `
            --app-version "1.0.0" `
            --vendor "Whisperer Team" `
            --copyright "Copyright 2025" `
            --dest whisperer-windows

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Executable
        run: |
          git add whisperer-windows
          git commit -m "Add Whisperer Windows executable [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
