name: Windows Build and Push Executable

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-push:
    name: Build and Push Executable for Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up WiX Toolset
      uses: wix/setup-wix@v1
      with:
        version: '3.11.2'

    - name: Grant gradlew execute permission
      shell: bash
      run: chmod +x gradlew

    - name: Build with Gradle
      run: .\gradlew.bat build shadowJar --info

    - name: Create output directory
      run: mkdir -p whisperer-windows

    - name: Create Windows executable
      run: |
        $jdkPath = "$env:JAVA_HOME"
        & "$jdkPath\bin\jpackage" `
          --input build/libs `
          --main-jar Whisprer-1.0-all.jar `
          --main-class com.example.whisprer.LauncherKt `
          --name "Whisperer" `
          --type msi `
          --win-console `
          --win-shortcut `
          --win-menu `
          --win-dir-chooser `
          --app-version ${env.GITHUB_REF_NAME#v} `
          --vendor "Whisperer Team" `
          --copyright "Copyright 2025" `
          --dest whisperer-windows

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push Executable
      run: |
        git add whisperer-windows
        git commit -m "Add Whisperer Windows executable [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
